[ADD] Answer.tsx 추가
StargateTeam/ProjectHub pull request #5
Opened 2021-12-18 17:04 UTC by unnew-main

그...일단 만드신 Button컴포넌트를 참고(카피)해서 돌아가는지 테스트를 해봤는데 enzyme-adapter 를 install하는데 react 버전 에러가 나서 구글링해보니 '@wojtekmaj/enzyme-adapter-react-17'로 하면 해결되기에 일단 저걸로 install했습니다. ... 테스트하는 방법에 대해서는 감이 오는데 뭘 테스트해야할지가 아직 느낌이 안와서 참고(카피)한 데이터로만 pr을 올립니다....

2021-12-18 17:36 UTC, KZ-Lucas commented
좋아요!!
제가 오늘은 일찍자야해서 내일 보고 리뷰할게요 :>

2021-12-20 03:30 UTC, GeunwonChoi commented on __test__/index.spec.tsx
> +Enzyme.configure({ adapter: new Adapter() });
jest는 setup 기능이 있습니다!

이 것을 활용하면 매 테스트 코드에 의무적으로 작성해야하는 코드를 최소화할 수 있어요.
나중에 제가 작성할 PR에 커밋 담아놓을테니 지금은 생각만 해둡시다!

2021-12-20 03:30 UTC, GeunwonChoi commented on __test__/index.spec.tsx
> +  const wrapper = shallow(<Answer size="lg" />);
size같은 attributes 는 {...props} 형태로 외부 props 객체를 선언해 drilling해주는 형태로 만들어주세요.

이래야 나중에 여러 컴포넌트에 대한 테스트 진행 시 매 describe 마다  props을 선언해주는 번잡한 코드들을 줄일 수 있습니다.

2021-12-20 03:30 UTC, GeunwonChoi commented on __test__/index.spec.tsx
> +  it('fontSize가 lg일 경우 FontSize는 30px 이어야함', () => {
여기 test 부분 desc가 이상한거같아요.

2021-12-20 03:30 UTC, GeunwonChoi commented on src/components/Answer.tsx
> +  return <input style={style} type="radio" />;
최종적으로 컴포넌트는 styled-component를 통해 export 된 컴포넌트를 리턴해 렌더링해주는 형태로 해줍시다.
(예, Answer.style.tsx)

이래야 나중에 스타일 처리가 편합니다.

2021-12-20 03:30 UTC, GeunwonChoi requested changes
강원도는 감자가 맛있어요.

2021-12-20 03:31 UTC, GeunwonChoi requested changes
뭐여 왜 reject가 없지

2021-12-26 08:26 UTC, unnew-main commented
기능: 전에 알려주신 기능들을 구현, 체크여부를 배열로 담아 css에 넘겨서 스타일변경  label도 클릭시 체크되는 기능
스타일: 체크하면 label글자색 변경

2022-04-22 06:24 UTC, JeongYunMi approved these changes

2022-04-23 10:01 UTC, KZ-Lucas approved these changes

2022-04-23 10:01 UTC, lucas0530 commented on __test__/index.spec.tsx
> +  const wrapper = shallow(<Answer size="lg" />);
Answer에 프롭은 객체를 통해 넘겨줍시다.
<Anwser {...props} />

이렇게 하는 이유는, 이후 렌더링 테스트에서 프롭을 좀더 유동적으로 변경하기 위함에 있습니다

2022-04-23 10:01 UTC, lucas0530 commented on __test__/index.spec.tsx
> +    expect(style.fontSize).toBe('20px');
테스트랑 Tobe Desc가 다른거같아요 20 >< 30

2022-04-23 10:01 UTC, lucas0530 commented on src/components/Answer.tsx
> +export const Answer = ({ size }: Props) => {
컴포넌트는 이전에 제가 말씀드렸던것처럼 *.style.tsx 스타일 컴포넌트를 하나 만들고, 스타일드 컴포넌트를 export하는 구조로 만들어주세요!

2022-04-23 10:01 UTC, lucas0530 commented on src/components/Answer.tsx
> +export const Answer = ({ size }: Props) => {
그래야 나중에 아래와 같은 스타일 처리가 요연해집니다.

2022-04-23 10:08 UTC, merged